image: docker:git

stages:
  - build
  - release

variables:
    IMAGE_NAME: registry.gitlab.com/quartic/weyl-build

build:
    stage: build
    script:
        - docker build -t $IMAGE_NAME .

release:
    stage: release
    script:
        - docker push $IMAGE_NAME
    only:
        - develop
