image: docker:git

services:
    - docker:dind

stages:
  - build

variables:
    IMAGE_NAME: registry.gitlab.com/quartic/weyl-build

build:
    stage: build
    script:
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
