---
# See:
# - https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/linux-repository.md
# - https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#use-docker-socket-binding

- name: Download setup script
  get_url: >
    url=https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh
    dest=/tmp/script.deb.sh

- name: Execute setup script
  command: bash /tmp/script.deb.sh
  become: true

- name: Install Gitlab-Runner
  apt: >
    name=gitlab-ci-multi-runner
    state=present
    update_cache=yes
  become: true

- name: Register runner
  command: gitlab-ci-multi-runner register -n \
    --url https://gitlab.com/ci \
    --registration-token pX8B2xgx6AKFteBeaRFE \
    --executor docker \
    --description "gitlab-runner" \
    --docker-image "docker:latest" \
    --docker-volumes /var/run/docker.sock:/var/run/docker.sock
